/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'oscar' at '9/02/16 9:25' with Gradle 2.6
 *
 * @author oscar, @date 9/02/16 9:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
